### PR TITLE
Pre-parsing refactor

### PR DESCRIPTION
**Pull request by kmokstad**
This retires the AppCommon-files, now only containing the AppXMLInputBase class.
Its replacement, SIMargsBase, also contains a method for parsing the parameter values from the command-line, such that the file-parsing and command-line parsing is located in the same source file.
I also put the adap-flag there, such that those Apps only using that in addition does not need a sub-class.

### CODE REVIEW

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-poisson=24 ifem-advectiondiffusion=16 ifem-darcy=12 ifem-ifem-stokes=85 please

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-poisson=24 ifem-advectiondiffusion=16 ifem-darcy=12 ifem-stokes=85 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-poisson=24 ifem-advectiondiffusion=16 ifem-darcy=12 ifem-stokes=85 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-poisson=24 ifem-advectiondiffusion=16 ifem-darcy=12 ifem-stokes=85 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-poisson=24 ifem-advectiondiffusion=16 ifem-darcy=12 ifem-stokes=85 please

**Pull request merged**
