### PR TITLE
Adaptivity in 1D

### PR DESCRIPTION
**Pull request by kmokstad**
This extends the ASMs1D class to also include stuff needed for adaptive refinement. It now inherit both ASMunstruct (used in AdaptiveSIM) and ASMstruct. ASMunstruct no longer inherit ASMbase.

### CODE REVIEW

**Comment by kmokstad** [comment]
For testing, Try LinEL -adap -1DKL on the input file
https://github.com/kmokstad/IFEM-Elasticity/blob/adap-1D/Linear/Test/SSbeamPointLoad-adap.xinp

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-elasticity=72 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-elasticity=72 ifem-openfrac=46 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-elasticity=72 ifem-finitedeformation=18 ifem-openfrac=46 please

**Comment by kmokstad** [comment]
I want to land this one next.
Guess we concluded last year that this approach for doing adaptivity in 1D is fine?

**Comment by akva2** [comment]
yes. i'll review it once more now.

**Comment by kmokstad** [comment]
I have now repsonded to all comments you wrote in #323, which actually (except for the last one) apply to this PR

**Pull request merged**
