### PR TITLE
Move patch-only dependent code from SIMinput to ASM-scope

### PR DESCRIPTION
**Pull request by kmokstad**
Some refactoring to make SIMinput cleaner.

There are two issues with this one that need some attention before this can be merged.

1. In ASMu2D::InterfaceChecker::Intersection (which I now changed into a std::pair, was done before the doxy arrived), I cannot see that the continuity flag (now the first member) is ever set or used. It is referred in the Stokes-app (the JumpCheckeru2D class), but where is it defined?

2. The second commit (SIM3D::clonePatches was missing) causes the 3D FSI tests to fail, due to the results are slightly off. Need to check whether it is the new or the old results that are the "correct" ones, and either update the tests for find the source of the error.

### CODE REVIEW

**Comment by kmokstad** [comment]
OK, as I said, it was changed into a pair because the previous struct was undocumented, and to minimize the needed doxy..., but since that has been changed now I can revert that part. But still it is not good with an uninitialized member (the continuity)

**Comment by akva2** [comment]
agree. initialize it to 0.

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-fsi=26 please

**Comment by kmokstad** [comment]
Regarding the second issue, I think the new response is the correct one. The difference was due to that the FSI solver thought the chorin sub-solvers were sharing the grids, but they were actually not. The result was then that only the velocity prediction solver got its grid updated when moving the structure, whereas the correction solvers worked on the initial grids all the way.

**Comment by kmokstad** [comment]
Det ble failure her. Men ser ikke noe annet galt enn de doxy-warningene?

**Comment by akva2** [comment]
ja, bare merge, hickup i doxygen scanneren (ser på det nå).

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-fsi=26 please

**Pull request merged**
