### PR TITLE
fix: don't use .back() for last node on element, use appropriate index

### PR DESCRIPTION
**Pull request by akva2**
global multipliers sit at the end.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
all tests pass. please review.

**Comment by timovanopstal** [comment]
looks fine to me

**Comment by kmokstad** [comment]
OK (I think), but check if the same fix apply to the other dimensions also (1D, 3D) as well as mixed

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by timovanopstal** [comment]
manual merge

**Pull request closed without merging**
