### PR TITLE
Fixed: Scalar component names on VTF

### PR DESCRIPTION
**Pull request by kmokstad**
If more than `nsd` components and a vector field name is provided as argument in SIMoutput::writeGlvS1(),
the scalar component names were duplicated. Also write exact vector field only if FE vector field is written.
With this fix the scalar component names will also be aligned with the names used on the HDF5 output,
which is an improvement by itself.

Don't dereference the myProblem pointer in writeGlvS() and writeGlvS1() without checking for null pointer first.

### CODE REVIEW

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-advectiondiffusion=82 ifem-boussinesq=107 ifem-thermoelasticity=35 ifem-navierstokes=212 ifem-fsi=74 please

**Review by akva2 — APPROVED** [review]
Once all tests are updated.

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-advectiondiffusion=82 ifem-boussinesq=107 ifem-thermoelasticity=35 ifem-navierstokes=212 ifem-fsi=74 ifem-hm=10 ifem-elasticity=161 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-advectiondiffusion=82 ifem-boussinesq=107 ifem-thermoelasticity=35 ifem-navierstokes=212 ifem-fsi=74 ifem-hm=10 ifem-elasticity=161 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-advectiondiffusion=82 ifem-boussinesq=107 ifem-thermoelasticity=35 ifem-navierstokes=212 ifem-fsi=74 ifem-hm=10 ifem-elasticity=161 ifem-beamex=37 please

**Pull request merged**
