### PR TITLE
Fixed: Using direction-dependent Gauss quadrature on face integrals

### PR DESCRIPTION
**Pull request by kmokstad**
This is needed for `<nGauss default="0"/>` to work properly when we have neumann conditions on 3D elements with different polynomial orders in the three parameter direction. Mostly for enabling correct export of traction vector arrows to VTF.

### CODE REVIEW

**Comment by kmokstad** [comment]
jenkins build this with downstreams please

**Comment by kmokstad** [comment]
jenkins build this with downstreams please

**Comment by kmokstad** [comment]
jenkins build this with downstreams please

**Review by akva2 — APPROVED** [review]
Possibly adding the threadGroup clear in ASMs2D as discussed on skype.

**Comment by kmokstad** [comment]
jenkins build this with downstreams please

**Pull request merged**
