### PR TITLE
changed: unify computeBasis signatures

### PR DESCRIPTION
**Pull request by akva2**
always take a spline pointer parameter. use reference in the NURBS interfaces.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Review by kmokstad — APPROVED** [review]
Looks fine as well, although I did not see the (good) reason for changing from pointer to reference on the spline argument for the computeBasisNurbs methods

**Comment by kmokstad** [comment]
and I assume the checks failure is unrelated

**Comment by akva2** [comment]
it's mostly my coding principles. using a pointer signals that null is an option and it's not an option in those methods. failure is the unit tests failing with clang, i'll rerun the build now.

**Pull request merged**
