### PR TITLE
RealFunc: add hessian() method

### PR DESCRIPTION
**Pull request by akva2**
For the reasons described in https://github.com/OPM/IFEM/pull/639 this adds the same for the second derivatives.

Sits on top of https://github.com/OPM/IFEM/pull/639

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-stokes=245 ifem-navierstokes=197 ifem-boussinesq=99 ifem-burgers=4 please

**Comment by akva2** [comment]
turns out there was a reason i had voigtIdx as a anon helper and not a lambda..

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Review by kmokstad — APPROVED** [review]
Yea, that's the downside of reviewing things in bits an pieces: I easily miss couplings like this. So back to file scope then.

**Pull request merged**
