### PR TITLE
Fix block matrix with single basis discretization

### PR DESCRIPTION
**Pull request by akva2**
- Print block matrix sizes in serial
- Put global lagrange multipliers in second block also with single basis method

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-stokes=192 please

**Comment by kmokstad** [comment]
@akva2 The test failure here means this is still WIP?

**Review by kmokstad — APPROVED** [review]
Can't spot any wrong doing here, so go ahead if you think the Test failure is nothing to worry about.

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-stokes=192 please

**Comment by akva2** [comment]
fine downstream..

**Pull request merged**
