### PR TITLE
fixed: mark constructor explicit to avoid unexpected implicit casts

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-navierstokes=58 please

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-navierstokes=58 ifem-elasticity=19 please

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-navierstokes=58 ifem-elasticity=19 ifem-finitedeformation=5 please

**Comment by akva2** [comment]
selv om (2 av) appene er fikset annerlundan, vil jeg fortsatt foretrekke at vi lander denne sanity-fiksen.

**Comment by kmokstad** [comment]
Greit det ja.

**Pull request merged**
