### PR TITLE
Arc length support

### PR DESCRIPTION
**Pull request by kmokstad**
Minor changes/fixes to support arc-length simulation driver in Elasticity

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-elasticity=64 ifem-beamex=15 please

**Comment by kmokstad** [comment]
@akva2 I don't see what was the problem here. The Console log from Jenkins just says:
```
Building downstream IFEM-Elasticity=pull/64/merge configuration=serial
~/workspace/IFEM-pr-builder ~/workspace/IFEM-pr-builder
Initialized empty Git repository in /var/lib/jenkins/workspace/IFEM-pr-builder/deps/IFEM-Elasticity/.git/
fatal: Couldn't find remote ref pull/64/merge
error: pathspec 'branch_to_build' did not match any file(s) known to git.
```
even though OPM/IFEM-Elasticity#64 did exist at that point.

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-elasticity=64 ifem-beamex=15 please

**Comment by kmokstad** [comment]
The branches are rebased now, but still the same failure..

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-elasticity=64 ifem-beamex=15 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-elasticity=64 ifem-beamex=15 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-elasticity=64 ifem-beamex=15 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-elasticity=64 ifem-beamex=15 please

**Pull request merged**
