### PR TITLE
Rename ASMmxBase::geoBasis to ASMmxBase::itgBasis

### PR DESCRIPTION
**Pull request by akva2**
More precise as this is the index of the integration basis.

Sits on top of https://github.com/OPM/IFEM/pull/615

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-stokes=236 ifem-navierstokes=191 ifem-boussinesq=95 please

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-stokes=236 ifem-navierstokes=191 ifem-boussinesq=95 please

**Review by kmokstad — APPROVED** [review]
I thought the first two commits already in #617. Not rebased yet?

**Comment by akva2** [comment]
yeah need to rebase. i had to force push master as i forgot a few tests and didn't want to have a fixup commit in there.

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-stokes=236 ifem-navierstokes=191 ifem-boussinesq=95 please

**Pull request merged**
