### PR TITLE
fix: array initialization for apple clang

### PR DESCRIPTION
**Pull request by timovanopstal**
same old apple stuff, but afraid of doing a premature self-merge.

### CODE REVIEW

**Comment by timovanopstal** [comment]
jenkins build this please

**Comment by timovanopstal** [comment]
downstreams not necessary, I only changed unit tests.

**Comment by timovanopstal** [comment]
all set...

**Comment by akva2** [comment]
once more for the crowd in the back

**Comment by akva2** [comment]
jenkins build this please

**Pull request merged**
