### PR TITLE
added: generate [Edge|Face]xPatches and InnerPatches topology sets

### PR DESCRIPTION
**Pull request by akva2**
these contain the patches touching the relevant boundary
and those not touching any boundary respectively.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by timovanopstal** [comment]
note: depends on #71

**Comment by VikingScientist** [comment]
Rebase and I'll review

**Comment by akva2** [comment]
done

**Comment by VikingScientist** [comment]
jenkins build this with downstreams please

**Comment by VikingScientist** [comment]
Looks good. I'll allow it :+1:

**Pull request merged**
