### PR TITLE
add: variations of stabilization params w.r.t. velocity

### PR DESCRIPTION
**Pull request by timovanopstal**
Required for consistent Jacobian matrices.

### CODE REVIEW

**Comment by timovanopstal** [comment]
jenkins build this stokes=28 navierstokes=28 with downstreams please

**Comment by timovanopstal** [comment]
hmm... have to rebase

**Comment by timovanopstal** [comment]
jenkins build this stokes=28 navierstokes=28 with downstreams please

**Comment by akva2** [comment]
build here ran with master, properly tested in downstream pr.

**Comment by akva2** [comment]
merged manually.

**Pull request closed without merging**
