### PR TITLE
Added: LinearFunc can also represent a piece-wise linear function

### PR DESCRIPTION
**Pull request by kmokstad**
The function value pairs are read from a multi-column ASCII file in an overloaded constructor.
Reimplemented class `Interpolate1D` using a `LinearFunc` object as member.
Added class `LinVecFunc` - a vector-valued piecewise linear function.

Functionality to be used in the DT Wind project.

### CODE REVIEW

**Comment by kmokstad** [comment]
jenkins build this with downstreams please

**Comment by kmokstad** [comment]
jenkins build this with downstreams please

**Review by akva2 — APPROVED** [review]
Looks good to me.

**Comment by kmokstad** [comment]
jenkins build this with downstreams please

**Pull request merged**
