### PR TITLE
 Added: XML-tag <robin> for the Robin-type boundary conditions 

### PR DESCRIPTION
**Pull request by kmokstad**
Instead of `<neumann type="generic" direction="-1">(something)</neumann>`.
With this, I'm not sure if we actually need type="generic" any more (are any of the "generic" neumann conditions still around something else than robin conditions)?

### CODE REVIEW

**Comment by akva2** [comment]
neumann type="generic" can all be robin, no problem there. it was just introduced as the terminology for neumann integrals handled by a separate integrand really.

**Comment by kmokstad** [comment]
OK, the may issue with the type="generic" convention is that you then force all Robin-BC's to use expressions, even when applied traction is zero or constant. Now you can use type="constant" also for these conditions (or leave out the type attribute which implies constant).

**Comment by akva2** [comment]
jenkins build this ifem-advectiondiffusion=31 ifem-thermoelasticity=14 ifem-stokes=117 ifem-navierstokes=101 ifem-fsi=40 ifem-boussinesq=12 with downstreams please

**Comment by kmokstad** [comment]
jenkins build this ifem-advectiondiffusion=31 ifem-thermoelasticity=14 ifem-stokes=117 ifem-navierstokes=101 ifem-fsi=40 ifem-boussinesq=12 with downstreams please

**Comment by kmokstad** [comment]
jenkins build this ifem-advectiondiffusion=31 ifem-thermoelasticity=14 ifem-stokes=117 ifem-navierstokes=101 ifem-fsi=40 ifem-boussinesq=12 with downstreams please

**Comment by kmokstad** [comment]
jenkins build this ifem-advectiondiffusion=31 ifem-thermoelasticity=14 ifem-stokes=117 ifem-navierstokes=101 ifem-fsi=40 ifem-boussinesq=12 with downstreams please

**Pull request merged**
