### PR TITLE
EvalMultiFunction: add automatic differentiation support

### PR DESCRIPTION
**Pull request by akva2**
Sits on top of https://github.com/OPM/IFEM/pull/647

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-stokes=245 ifem-navierstokes=197 ifem-boussinesq=99 ifem-burgers=4 ifem-elasticity=150 please

**Review by kmokstad — APPROVED** [review]
Looks OK. However, I'm not too fond of class names `<whatever>Impl` only for making unique names. (All classes implement something.) Propose the following names instead:

- EvalFuncScalar instead of EvalFuncImpl
- EvalFuncSpatial instead of EvalFunctionImpl

Then the names more indicate that the former is function with a scalar argument, whereas the latter has a spatial argument. You can still keep the type aliases to avoid effects elsewhere.

**Comment by akva2** [comment]
Fair enough, I'm not at all tied to the impl.

For the record it is meant to imply that it's the implementation, not that it implements something :).

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Pull request merged**
