### PR TITLE
changed: make failed.log updates atomic in regression tests

### PR DESCRIPTION
**Pull request by akva2**
this to obtain a proper failed.log even if running multiple tests
in parallel

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
silence is acceptance?

**Review by kmokstad — APPROVED** [review]

**Pull request merged**
