### PR TITLE
Skew-symmetric convection

### PR DESCRIPTION
**Pull request by timovanopstal**
add skew-symmetric form of convection to weak operators.

### CODE REVIEW

**Comment by akva2** [comment]
this part is fine.

**Comment by timovanopstal** [comment]
since @akva2 review: fixed bug in conservative convection (reflected in NavierStokes reg test) and decided to avoid using Advection for convective form as well: for consistent notation -- do you agree?

**Comment by akva2** [comment]
sure, not a problem. i'd inline it when moving to blas in any case.

**Comment by timovanopstal** [comment]
status: ready to rebase/test/merge after #92 and #94

**Comment by timovanopstal** [comment]
jenkins build this with downstreams ifem-stokes=40 ifem-navierstokes=38 please

**Pull request merged**
