### PR TITLE
Changed: Use ScalarFunc instead of RealFunc for max iterations.

### PR DESCRIPTION
**Pull request by kmokstad**
Fixed: getMaxit() should always return 0 when staggering is disabled.
Added: Method to initialize parameters from an xml-tag.

### CODE REVIEW

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-opfenfrac=61 ifem-boussinesq=52 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-openfrac=61 ifem-boussinesq=52 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-openfrac=61 ifem-boussinesq=52 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-openfrac=61 ifem-boussinesq=52 please

**Review by akva2 — APPROVED** [review]

**Pull request merged**
