### PR TITLE
Fix LR dirichlet boundary conditions

### PR DESCRIPTION
**Pull request by akva2**
Nodes in edgeCurve were sorted, but nodes in getEdgeNodes were not.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-poisson=4 please

**Comment by VikingScientist** [comment]
All checks have failed?

**Comment by akva2** [comment]
yes, fails in poisson, i haven't looked into it yet.

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-poisson=4 please

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-poisson=4 please

**Comment by VikingScientist** [comment]
Per skype discussion: This issue is more fundamental than simply re-ordering the control points and wrapping into a `Go::SplineCurve`. I don't know if we should include this as an "intermediate fix" which will improve on the current situation, but not completely resolve it, or if we should scrap this altogether and start over again?

**Comment by akva2** [comment]
let's just get it right once and for all. we're not in that much of a hurry that we need a slightly better solution now.

**Comment by timovanopstal** [comment]
superseded by #84

**Pull request closed without merging**
