### PR TITLE
make single-parameter constructors as explicit

### PR DESCRIPTION
**Pull request by akva2**
to avoid unexpected implicit casts

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
once more with better timing.

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by kmokstad** [comment]
I see you already merged this, even before I just noticed it was opened a separate PR for it. But that's fine this one. The only thing I could point on is when the constructor is protected, such explicit declaration seems unnecessary, since it then will be visible for sub-classes only. Then less (or no) danger for the mentioned auto-casting issues? Similar for private nested classes. But of course it will not cause any harm either, so this is just a comment.

**Comment by akva2** [comment]
I agree. Sadly cppcheck doesnt..

**Pull request merged**
