### PR TITLE
New class SIMsolution for better serialization/restart support

### PR DESCRIPTION
**Pull request by kmokstad**
The main thing is the introduction of the SIMsolution class, which now holds the solution vectors to be stored on file in case of restart. Apps needing restart support then inherit this class to get the serialization feature. This is also used in the nonlinear/dynamic solution drivers.

### CODE REVIEW

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-elasticity=57 ifem-thermoelasticity=12 ifem-poroelasticity=25 ifem-advectiondiffusion=21 ifem-finitedeformation=15 ifem-beamex=14 ifem-stokes=102 ifem-navierstokes=88

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-elasticity=57 ifem-thermoelasticity=12 ifem-poroelasticity=25 ifem-advectiondiffusion=21 ifem-finitedeformation=15 ifem-beamex=14 ifem-stokes=102 ifem-navierstokes=88

**Comment by akva2** [comment]
How rude. Remember to say please.

**Comment by akva2** [comment]
jenkins build this with downstreams ifem-elasticity=57 ifem-thermoelasticity=12 ifem-poroelasticity=25 ifem-advectiondiffusion=21 ifem-finitedeformation=15 ifem-beamex=14 ifem-stokes=102 ifem-navierstokes=88 please

**Pull request merged**
