### PR TITLE
fixed: allow flat dump format

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Review by kmokstad — APPROVED** [review]
Alternatively, one could accept `format == "flat"` and/or `fornmat == "plain"`, etc. before giving the error.

**Comment by akva2** [comment]
yeah, i was uncertain whether we want to force a format attribute in that case or not. if you think it's better, i can do that.

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Pull request merged**
