### PR TITLE
ASMu2Dmx: use computeBasis wrappers

### PR DESCRIPTION
**Pull request by akva2**
Sits on top of https://github.com/OPM/IFEM/pull/589

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
i accidentially pushed this before review. but should be not be controversial.

**Review by kmokstad — COMMENTED** [review]
Indeed, only switching computeBasis method to use. I approve it hereby in retrospect ;-)

**Pull request closed without merging**
