### PR TITLE
fixed: set parameters when projecting function

### PR DESCRIPTION
**Pull request by akva2**
necessary when using a fieldfunction

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Review by kmokstad — APPROVED** [review]
Looks fine, but maybe also rewrite the `xi`assignment using a loop while at it, for increased readability:
```
  for (size_t j = 0; j < 3 & j < m_patch.getNoSpaceDim(); j++)
    xi[j] = u[j][0] + gpar[j][i] / (u[j][1] - u[j][0]);
```

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Pull request merged**
