### PR TITLE
Added: Assembly of scalar quantities together with the equation system.

### PR DESCRIPTION
**Pull request by kmokstad**
Added: Debug print of extracted element solution vectors.
Changed: Default value of argument witRF in SIMbase::initSystem to false.
Changed: Removed three spaces in the summary print for scalar solutions.

No merge yet, companion to the staggered branch for OpenFrac

### CODE REVIEW

**Comment by kmokstad** [comment]
jenkins build this with downstreams please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-poisson=14 ifem-elasticity=12 ifem-openfrac=20 please

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-poisson=14 ifem-elasticity=12 ifem-openfrac=20 ifem-darcy=6 ifem-fsi=35 please

**Comment by kmokstad** [comment]
Her er noe muffens, det står All checks have failed i rødt, men når jeg trykker på Details kommer det opp 0 failures, så hva er det da somer galt?

**Comment by notspiff** [comment]
Den feilet i byggefasen, se console output

**Comment by kmokstad** [comment]
jenkins build this with downstreams ifem-poisson=14 ifem-elasticity=12 ifem-openfrac=20 ifem-darcy=6 ifem-fsi=11 please

**Pull request merged**
