### PR TITLE
Fixed: Determinant of second-order symmetric tensors

### PR DESCRIPTION
**Pull request by TheBB**

### CODE REVIEW

**Comment by akva2** [comment]
extend tests please.

**Comment by TheBB** [comment]
I added some test *code*, not sure where to point cmake to it. It doesn't run here at least. Is it just picked up at configure time?

**Comment by akva2** [comment]
yes, it's grepped on configure time. just rerun cmake.

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by TheBB** [comment]
Feel free!

**Comment by akva2** [comment]
oh, and in the future please don't push feature branches directly to the upstream repo.

**Comment by TheBB** [comment]
Yeah, I noticed too late where origin was pointed, and I didn't want to re-open another PR.

**Comment by TheBB** [comment]
Closed for #291

**Pull request closed without merging**
