### PR TITLE
Bugfix in 3D LR recovery

### PR DESCRIPTION
**Pull request by VikingScientist**

### CODE REVIEW

**Comment by akva2** [comment]
i think it would be wise to flip the fix. nothing else in asm interface speaks 0 indices. sure, it's internal but...

**Comment by VikingScientist** [comment]
`getElementCoordinates()` and `getParametricVolume()` used right above this both takes 1-indexed input.

**Comment by akva2** [comment]
yes, which was my point. or i don't follow.

**Comment by akva2** [comment]
just in case my formulation was unclear: i think it's better to do the subtraction inside getGaussParameters instead of in the caller code to have it behave the same - 1-based indices going into the function.

**Comment by VikingScientist** [comment]
oh... I was under the impression that the entire `iel`-variable should be 0-based, but in the `ASMu3D::assembleL2matrices` it needs to be used as both 0 and 1. But you area right, one might make it 1-indexed inside `ASMu3D::getGaussPointParameters`. I'll fix this tomorrow.

**Comment by akva2** [comment]
It is 0 based when interacting with SAM. I think that was the system i found in the madness at some point.

**Comment by VikingScientist** [comment]
jenkins build this please

**Comment by VikingScientist** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this with downstreams

**Comment by akva2** [comment]
all good, going in.

**Pull request merged**
